# Generated by Django 4.1.7 on 2023-03-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receipts", "0003_expensecategory_alter_receipt_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="date",
            field=models.DateTimeField(null=True),
        ),
    ]
